#ifndef __SPADES_CONFIG_HPP__
#define __SPADES_CONFIG_HPP__

#define SPADES_USE_JEMALLOC
/* #undef SPADES_USE_TCMALLOC */
#define SPADES_DEBUG_LOGGING
/* #undef SPADES_ENABLE_EXPENSIVE_CHECKS */

#endif // __SPADES_CONFIG_HPP__
